export const HOME = 'Home';
export const RAEDER = 'Reader';
export const ITEMDETAILS = 'Item Details';
export const ITEMLIST = 'User List';
export const REGISTER = 'Register';
export const LOGIN = 'Login';
export const FORGOTPASSWORD = 'forgotPassword';
export const USERMANAGER = 'User Manager';
export const BORROWERS = 'Borrowers'
export const INVESTMENTS = 'Investments'
export const LOSSES = 'Losses'
export const INCOME = 'Income'
export const EXPENSES = 'Expenses'
export const LOANTO = 'Loan To'
export const FUNDTRANSFER = 'Fund Transfers'
export const NOTICES = 'Notices'
export const PROPOSALS = 'Proposals'
export const PROJECTS = 'Projects'
